import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import ThemeRegistry from "../theme/ThemeRegistry";
import Footer from "../components/layout/Footer";
import Navbar from "../components/layout/Navbar";
// import "@/globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "REBELS",
  description: "Generated by REBELS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ThemeRegistry>{children}</ThemeRegistry>
        <Footer />
      </body>
    </html>
  );
}
